[mypy]
python_version = 3.9
mypy_path = src
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
check_untyped_defs = True

[mypy-psutil]
ignore_missing_imports = True

[mypy-pynput]
ignore_missing_imports = True

[mypy-pynput.*]
ignore_missing_imports = True

[mypy-requests]
ignore_missing_imports = True

[mypy-pandas]
ignore_missing_imports = True

[mypy-scipy]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-statsmodels]
ignore_missing_imports = True

[mypy-statsmodels.*]
ignore_missing_imports = True

[mypy-sklearn]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-win32gui]
ignore_missing_imports = True

[mypy-win32process]
ignore_missing_imports = True

; Made with Bob
